export default [
    {
        id:1,
        name:'image1',
        src:'/images/home_image/Image_1.jpg',
        alt:'image1',
        href:'/gallery',
        href_content:'Our Gallery',
        content1:'Explorer of visual poetry',
        content2:'Art is not static, It is evolving as your perception changes. Love is not what you do, love is what you are.',
    },
    {
        id:2,
        name:'image2',
        src:'/images/home_image/Image_2.jpg',
        alt:'image2',
        href:'/about',
        href_content:'About Us',
        content1:'Countryside, great sunshine',
        content2:'The bright sunlight covers the picture, and the quiet and relaxing countryside scenery, in the film color and grain sense, shows the intoxicant atmosphere. Summer has arrived, a group of nostalgic style fashion works, open this unusual summer.',
    },
    {
        id:3,
        name:'image3',
        src:'/images/home_image/Image_3.jpg',
        alt:'image3',
        href:'/service/personal#1',
        href_content:'Our Services',
        content1:'Respect on history',
        content2:'There are many misunderstandings about "documentary". The most obvious one is to recognize only one way you agree with and to scorn the other. However, the premise of evaluation is to make clear their own Angle and position, and at least keep a respectful attitude toward the works that cannot be included in their vision. The recognition of a plurality is the starting point of all evaluation.',
    },
]